spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-Class-Name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/postgres
#    url: jdbc:postgresql://postgres:5432/postgres
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: postgres
    password: 123

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
jwt:
  secret: secret

notification:
  shop-mail: skishop@gmail.com
  url: localhost:8082

#logging:
#  level:
#    root: debug
#    org.springframework.web: debug
#    org.hibernate: error