spring:
  datasource:
    driver-Class-Name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: navvrks9
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true