spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-Class-Name: org.postgresql.Driver
    url: ${DATABASE_URL:jdbc:postgresql://host.docker.internal:5432/postgres}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:123}

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

jwt:
  secret: secret

notification:
  shop-mail: ${SHOP_MAIL:skishop@gmail.com}
  url: ${NOTIFICATION_URL:host.docker.internal:8082}