spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-Class-Name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: navvrks9

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
jwt:
  secret: secret

#logging:
#  level:
#    root: debug
#    org.springframework.web: debug
#    org.hibernate: error